GET "https://coronavirus-monitor.p.rapidapi.com/coronavirus/worldstat.php" HTTP/1.1
Content-Type: application/json

{
 	"x-rapidapi-key": "7887d314femsh169290428000428p199f93jsn9470329ba9cb",
	"x-rapidapi-host": "coronavirus-monitor.p.rapidapi.com"
}